### ISSUE TITLE
reikšmė reikšmė -> reikšmė

### ISSUE THREAD

**Issue by Agne21** [mokymai/taisymai-2024#101]
### Nuoroda

https://mokymai.github.io/konspektas/aprasomoji-1.html

### Ekrano nuotrauka su pažymėtais netikslumais

![IMG_6352](https://github.com/user-attachments/assets/d3f64d62-ceee-4ae5-b56c-e88d4218e2c9)

### Netikslumo tipas

stilius, kita

### Netikslumo tekstas su keliais žodžiais aplinkui

imties kvantilis yra reikšmė reikšmė už kurią

### Netikslumo tekstas

,,reikšmė reikšmė”

### Siūlomas taisymo tekstas

1 kartą parašytas žodis: ,,reikšmė”

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
- Dubliuoja #93
