### ISSUE TITLE
teorija: dalyboje esantys skaičiai sukeisti vietomis → apkeisti skaičius vietomis (neteisingai parašyta dalyba duoda gerą atsakymą)

### ISSUE THREAD

**Issue by Giedre2024** [mokymai/taisymai-2024#104]
### Nuoroda

https://mokymai.github.io/konspektas/aprasomoji-1.html

### Ekrano nuotrauka su pažymėtais netikslumais

![image](https://github.com/user-attachments/assets/c3708609-3d53-4118-9826-4ae58a233c9a)

### Netikslumo tipas

skaičiavimo klaida

### Netikslumo tekstas su keliais žodžiais aplinkui

Variacijos koeficientas

### Komentaras

Tai yra 3-ioje temoje: ''Skaitiniai metodai vienam kintamajam"

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
- Dubliuoja #91
