### ISSUE TITLE
P04-1 (v1.6) sk. 63: situacijos → situacijoms (skaidrės)

### ISSUE THREAD

**Issue by Kamile-Dzisevic** [mokymai/taisymai-2024#112]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P04-1 v1.6 
4. **Skaidrės numeris:** 63 
5. **Glaustai aprašykite netikslumą:** rašybos klaida

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Vienoms situacijos labiau 
7. **Netikslumo tekstas:** situacijos
8. **Siūlomas taisymo tekstas:** situacijoms
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta. 
<img width="533" alt="image" src="https://github.com/mokymai/taisymai-2024/assets/159070758/2256e813-bb84-44bf-bf5f-06fca8021dea">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Šioje skaidrėje nr. 63 nerandu nurodyto netikslumo:

![image](https://github.com/mokymai/taisymai-2024/assets/12725868/6097af5b-667b-42e5-92fa-9b3bfea0f18d)

**Comment by Kamile-Dzisevic** [comment]
> Šioje skaidrėje nr. 63 nerandu nurodyto netikslumo:
> 
> ![image](https://private-user-images.githubusercontent.com/12725868/327747828-6097af5b-667b-42e5-92fa-9b3bfea0f18d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDM1MjcsIm5iZiI6MTcxNDc0MzIyNywicGF0aCI6Ii8xMjcyNTg2OC8zMjc3NDc4MjgtNjA5N2FmNWItNjY3Yi00MmU1LTkyZmEtOWIzYmZlYTBmMThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDEzMzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMzM0NzRiYTNhMDhjYWYxNDMzODNkNGZiYmEwZmEwZmU5ODU1ODU3YzQ0ZDg5NWNiMDZjZjAyODE1MjY1NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qazzIlwE_EhHvvNMUAZ54ML_iWTEZSX6jad7KeN6eNI)

Netikslumas yra paskutinėje skaidrės eilutėje antras žodis "situacijos" (tai pažymėta ir mano screenshote).
Kaip suprantu, "situacijos" turėtų būti suderintas su žodžiu "vienoms", taigi, tada turėtų būti užrašyta "situacijoms".
