### ISSUE TITLE
[teorija]: atlikdami tyrimą įprastai→ atlikdami tyrimą, įprastai (skyryba)

### ISSUE THREAD

**Issue by LauraKochanauskaite** [mokymai/taisymai-2024#118]
### Nuoroda

https://mokymai.github.io/konspektas/ats-d-skirstiniai.html

### Ekrano nuotrauka su pažymėtais netikslumais

<img width="308" alt="image" src="https://github.com/user-attachments/assets/a1ec8078-a1cb-4b2d-ba91-cacbbe74d5d4">

### Netikslumo tipas

skyryba

### Netikslumo tekstas su keliais žodžiais aplinkui

Atlikdami tyrimą įprastai iš imties, kuri yra....

### Netikslumo tekstas

Atlikdami tyrimą įprastai...

### Siūlomas taisymo tekstas

Atlikdami tyrimą, įprastai...

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Neprivaloma skyryba
