### ISSUE TITLE
[BS-pratybos]: bus #| sukurtas → bus sukurtas (papildomi simboliai)

### ISSUE THREAD

**Issue by BarteZiliukaite** [mokymai/taisymai-2024#12]
1. **Dalykas:** BS-2024
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/biochemikams/01--BS-2024--s01--intro-r-rs.html#r-aritmetika
4. **Glaustai aprašykite netikslumą:**  pertekliniai simboliai tekste (#|)

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** aplanko, kuriame jis bus #| sukurtas (6) pavadinimus 
6. **Netikslumo tekstas:** bus #| sukurtas
7. **Siūlomas taisymo tekstas:** bus sukurtas
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://github.com/user-attachments/assets/616a407d-68b4-40f8-b46b-339af4dfe42a)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Sveiki, ši klaida buvo pataisyta. Jums kažkodėl rodo senesnę svetainės versiją.
Pabandykite atsidaryti kitoje naršyklėje.
