### ISSUE TITLE
[pratybos]: max_sepal_width = max(Sepal.Width), (kodo klaida)

### ISSUE THREAD

**Issue by LauraMilak** [mokymai/taisymai-2024#127]
### Nuoroda

https://mokymai.github.io/biochemikams/s07.html#funkcija-summarize

### Ekrano nuotrauka su pažymėtais netikslumais

![Screenshot 2024-10-22 at 23 25 30](https://github.com/user-attachments/assets/d969a377-27ee-4b7c-9cf5-20642e4fa1e8)

### Netikslumo tipas

kita

### Netikslumo tekstas su keliais žodžiais aplinkui

max_sepal_width = max(Sepal.Width),

### Netikslumo tekstas

max_sepal_width = max(Sepal.Width),

### Siūlomas taisymo tekstas

max_sepal_width = max(Sepal.Width)

### Komentaras

Po paskutinio veiksmo summarize nebereikia naudoti kablelio

### Dalykas

BS-2024

### Dėstytojas, kuris rengė medžiagą

Vilmantas

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Ar jums kodo vykdymas užstringa? Naujausia versija (bent Windows kompiuteryje) leidžia papildomus kablelius:

![image](https://github.com/user-attachments/assets/c77b3ec7-0ef0-4cf7-bfa5-210c1464cfaf)

Išbandykite:
```r
iris |>
  summarize(
    median_sepal_length = median(Sepal.Length),
    max_sepal_length = max(Sepal.Length),
    max_sepal_width = max(Sepal.Width),
  )
```
