### ISSUE TITLE
[pratybos]: virs → virš (netinkama raidė)

### ISSUE THREAD

**Issue by Loreta-St** [mokymai/taisymai-2024#144]
### Nuoroda

https://mokymai.github.io/biochemikams/s07.html

### Ekrano nuotrauka su pažymėtais netikslumais

![image](https://github.com/user-attachments/assets/e016bf8d-8e47-4227-aa89-89f7aaa3ef20)

### Netikslumo tipas

rašyba (praleista raidė ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

names_from: stulpelį, kurio reikšmės virs stulpelių pavadinimais.

### Netikslumo tekstas

virs

### Siūlomas taisymo tekstas

virš

### Dalykas

BS-2024

### Dėstytojas, kuris rengė medžiagą

Vilmantas

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
?
