### ISSUE TITLE
[BS-teorija]: skirsiniai → skirstiniai(praleista raidė)

### ISSUE THREAD

**Issue by Agne21** [mokymai/taisymai-2024#16]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** Teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** ... https://mokymai.github.io/konspektas/ 
4. **Glaustai aprašykite netikslumą:**  ... Gramatikos klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  ,,Įprastai skirsiniai nurodo galimas…”
7. **Netikslumo tekstas:** ... ,,skirsiniai”
8. **Siūlomas taisymo tekstas:** ... Taisau į ,,skirstiniai”
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![IMG_5864](https://github.com/user-attachments/assets/cc066883-081c-4eaa-bb03-da43ef8055d7) 

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
@Agne21, dėkoju už pranešimą. Visgi, jo pavadinimas turi būti informatyvus, kad kiti studentai net neatsidarę pranešimo iš pavadinimo žinotų, apie ką jis. Prašau pataisyti pavadinimą ir balai bus įskaityti.

Informatyvaus pavadinimo pavyzdys:
`[BS-teorija]: skirsiniai → skirstiniai (praleista raidė)`
