### ISSUE TITLE
P06-7 (v1.0): saičiuoti → skaičiuoti (skaidrės)

### ISSUE THREAD

**Issue by LauraZapasnikaite** [mokymai/taisymai-2024#161]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** BS-2024--P06-7--pi-pasirinkimo-schema--(v1.0)
4. **Glaustai aprašykite netikslumą:** rašybos klaida
5.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Ne, reikia saičiuoti kitus dalykus
6. **Netikslumo tekstas:** saičiuoti
7. **Siūlomas taisymo tekstas:** skaičiuoti
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta. 

<img width="482" alt="image" src="https://github.com/mokymai/taisymai-2024/assets/159000673/9ef01ccf-8903-4770-a46d-e4222ca839a4">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
- #142
