### ISSUE TITLE
[BS-teorija]: Ka → Kas (praleista raidė)

### ISSUE THREAD

**Issue by Agne21** [mokymai/taisymai-2024#17]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** Teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** ... https://mokymai.github.io/konspektas/ 
4. **Glaustai aprašykite netikslumą:**  ... Praleista raidė

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  ,,Ka yra trūkstama reikšmė?”
6. **Netikslumo tekstas:** ... ,,Ka”
7. **Siūlomas taisymo tekstas:** ... Taisau į ,,Kas”. 
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
[...]
![IMG_5866](https://github.com/user-attachments/assets/f1acb5b0-19db-4ea2-b636-633c095241c7)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
@Agne21, pavadinimą pakeiskite į:
`[BS-teorija]: Ka → Kas (praleista raidė)`
