### ISSUE TITLE
P141-1 (v1.0) sk.4: poromis → pora

### ISSUE THREAD

**Issue by Agne21** [mokymai/taisymai-2024#170]
### Ekrano nuotrauka su pažymėtais netikslumais

![IMG_8039](https://github.com/user-attachments/assets/332c0e75-06e8-44a6-b181-11385bd0373d)

### Netikslumo tipas

gramatika (nesuderinti linksniai ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

,,kiekviena poromis”

### Netikslumo tekstas

poromis

### Siūlomas taisymo tekstas

į pora

### Komentaras

su ‘kiekviena pora’

### Dalykas

BS-2024

### Netikslumo vieta

skaidrės

### Patvirtinimas

- [X] Temos pavadinime nurodžiau skaidrių bloko kodą, versiją ir skaidrės numerį.
- [X] Temos pavadinime nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Nematau, kur klaida: lyginama poromis kiekviena grupė su kiekviena grupe, o ne grupė su grupių pora.
