### ISSUE TITLE
[Emokymai]: Emkymai → Emokymai (rašyba, U04 III dalyje)

### ISSUE THREAD

**Issue by EmaDaraciute** [mokymai/taisymai-2024#186]
1. **Dalykas:** BS-2024
2. **Netikslumo vieta:** „Emokymai“ svetainė
3. **Nuoroda į resursą (URL):** https://emokymai.vu.lt/mod/assign/view.php?id=250063
4. **Glaustai aprašykite netikslumą:** rašybos klaida 
6. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** atsakymais (qmd ir HTML) įkelkite į „Emkymai“ 
7. **Netikslumo tekstas:** Emkymai
8. **Siūlomas taisymo tekstas:** Emokymai
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://github.com/mokymai/taisymai-2024/assets/159481926/e69c453e-4f0a-42ea-8880-289fd34c2d24)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
- #186
- #191
- #196
