### ISSUE TITLE
P07-3 (v1.2) sk.13: vengiama → vengiamos (skaidrės)

### ISSUE THREAD

**Issue by LauraZapasnikaite** [mokymai/taisymai-2024#188]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** BS-2024--P07-3--ht-klaidos-kriterijaus-galia--(v1.2)
4. **Skaidrės numeris:** 13
5. **Glaustai aprašykite netikslumą:** rašybos klaida
6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** t. y., pirmos rūšies klaidos labiau vengiama.
7. **Netikslumo tekstas:** vengiama
8. **Siūlomas taisymo tekstas:** vengiamos
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta. 
<img width="557" alt="image" src="https://github.com/mokymai/taisymai-2024/assets/159000673/120aa721-2eb7-4cc1-b3df-638856b8ef42">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Ko vengiama – klaidõs (vienaskaita).
