### ISSUE TITLE
[Emokymai]: "Emkymai" → "Emokymai" (rašybos klaida)

### ISSUE THREAD

**Issue by Akvor** [mokymai/taisymai-2024#196]
1. **Dalykas:** BS-2024
2. **Netikslumo vieta:** „Emokymai“ svetainė
3. **Nuoroda į resursą (URL):** https://emokymai.vu.lt/mod/assign/view.php?id=252878
4. **Glaustai aprašykite netikslumą:** rašybos klaida : Emkymai, o ne Emokymai.
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  įkelkite į „Emkymai“
6. **Netikslumo tekstas:**  „Emkymai“
7. **Siūlomas taisymo tekstas:** "Emokymai"
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://github.com/mokymai/taisymai-2024/assets/134396765/c9497a7f-db7d-4e7d-91c3-f435f4b1609e)

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
- #191
