### ISSUE TITLE
P06-3--stat-isvados-(v1.0)-sk.5: reprezentyvi → reprezentatyvi (rašyba)

### ISSUE THREAD

**Issue by ainaelravvas** [mokymai/taisymai-2024#215]
### Ekrano nuotrauka su pažymėtais netikslumais

![image](https://github.com/mokymai/taisymai-2024/assets/159725354/e7feee72-b6b5-4808-a123-5d7c6f752220)

### Netikslumo tipas

rašyba (praleista raidė ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

Imtis reprezentyvi: gerai atitinka GA

### Netikslumo tekstas

reprezentyvi

### Siūlomas taisymo tekstas

reprezentatyvi

### Komentaras

galbūt yra ir vartojamas terminas reprezentyvi, bet aš internete neradau :)

### Dalykas

BS-2024

### Netikslumo vieta

skaidrės

### Patvirtinimas

- [X] Temos pavadinime nurodžiau skaidrių bloko kodą, versiją ir skaidrės numerį.
- [X] Temos pavadinime nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Čia klaida. Dėkui.
