### ISSUE TITLE
P08-4 (v1.2) sk.31: it→ ir (rašybos klaida)

### ISSUE THREAD

**Issue by kuliesyte** [mokymai/taisymai-2024#221]
### Ekrano nuotrauka su pažymėtais netikslumais

![image](https://github.com/mokymai/taisymai-2024/assets/161529399/d6a4b9db-02e5-4e84-a9f7-e4046bb4bd11)

### Netikslumo tipas

rašyba (praleista raidė ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

Interpretuojamas it vertinamas taip pat, kaip Goodman-Kruskal 

### Netikslumo tekstas

it

### Siūlomas taisymo tekstas

ir

### Dalykas

BS-2024

### Netikslumo vieta

skaidrės

### Patvirtinimas

- [X] Temos pavadinime nurodžiau skaidrių bloko kodą, versiją ir skaidrės numerį.
- [X] Temos pavadinime nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
- #187
