### ISSUE TITLE
[BS-teorija]: pradine(žaliavine) → pradinė(žaliavinė) (rašyba)

### ISSUE THREAD

**Issue by LauraKochanauskaite** [mokymai/taisymai-2024#32]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** Teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** https://mokymai.github.io/konspektas/01--01--pradines-savokos.html#sec-stat-tyrimu-planavimas
4. **Glaustai aprašykite netikslumą:**  Vietoje ė raidės parašytos e raidės.
 Rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  Nafta yra išgaunama dideliais kiekiais, bet pradine (žaliavine) forma nėra itin naudinga.
6. **Netikslumo tekstas:** Pradine(žaliavine)
7. **Siūlomas taisymo tekstas:** Pradinė(žaliavinė)
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="439" alt="image" src="https://github.com/user-attachments/assets/69b29847-32a9-44ff-84ea-620634ec98da">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
- #23
