### ISSUE TITLE
[BS-teorija]: Įptastinė → Įprastinė (rašybos klaida)

### ISSUE THREAD

**Issue by LauraKochanauskaite** [mokymai/taisymai-2024#35]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** Teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** https://mokymai.github.io/konspektas/01--01--pradines-savokos.html#sec-stat-tyrimu-planavimas
4. **Glaustai aprašykite netikslumą:**  Vietoje r raidės yra parašyta t raidė
 Rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  1.6.1 Įptastinė statistinio tyrimo eiga
6. **Netikslumo tekstas:** Įptastinė
7. **Siūlomas taisymo tekstas:** Įprastinė
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="412" alt="image" src="https://github.com/user-attachments/assets/45b89c5f-0cb3-4487-a15d-577ed4f1f01b">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
- #9
