### ISSUE TITLE
[BS-teorija]: Skirsiniai→ Skirstiniai (rašyba)

### ISSUE THREAD

**Issue by LauraKochanauskaite** [mokymai/taisymai-2024#37]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** Teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** https://mokymai.github.io/konspektas/01--01--pradines-savokos.html#sec-stat-tyrimu-planavimas
4. **Glaustai aprašykite netikslumą:**  trūksta t raidės
 rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  Įprastai skirsiniai nurodo galimą reikšmę (ar jų intervalą) bei su tuo susietą reikšmių skaičių (statistinį dažnį), (procentinę) dalį arba tikimybę.
6. **Netikslumo tekstas:** Skirsiniai
7. **Siūlomas taisymo tekstas:** Skirstiniai
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="431" alt="image" src="https://github.com/user-attachments/assets/46384b26-8158-4ada-93b7-779b9824fcbe">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
- #16

**Comment by GegznaV** [comment]
Prieš tai #16 turėjo neinformatyvi etiketę.
