### ISSUE TITLE
[BS-pratybos]: Rekomenduojamų paketų diegimo programa neveikia Linux sistemose -> pakeisti pkgType = "both" į pkgType = "source"

### ISSUE THREAD

**Issue by brch-01** [mokymai/taisymai-2024#42]
1. **Dalykas:** BS-2024
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** [Reikiamų paketų diegimas](https://mokymai.github.io/programa-r/diegimas.html#reikiamu-paketu-diegimas)
4. **Glaustai aprašykite netikslumą:**  Suderinamumo klaida. Nurodytas paketų diegimo kodas neveikia Linux sistemose, kadangi `pkgType = "both"` yra palaikomas tik Windows ir iOS operacinėse sistemose. 

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**
```R
options(
  repos = "https://cran.rstudio.com/",
  pkgType = "both",
  install.packages.check.source = "no",
  install.packages.compile.from.source = "never" # "interactive"|"always"|"never"
)
```
 
6. **Netikslumo tekstas:** `pkgType = "both"`
7. **Siūlomas taisymo tekstas:** `pkgType = "source"`
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://github.com/mokymai/taisymai-2024/assets/122394978/5c0de37a-f149-466d-8082-76c504ea5860)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Ši dalis yra pataisyta. Pabandykite perkrauti tinklalapį arba naudokite kitą naršyklę.

**Comment by GegznaV** [comment]
`pkgType = "source"` nėra tinkamas Windows, nes reikalautų kelių GB dydžio papildinio paketus diegti tokiu būdu.


Bet kuriuo atveju, dėkoju už pranešimą.
