### ISSUE TITLE
[teorija]: su statistika susijusius → ,su statistika susijusius, (skyryba)

### ISSUE THREAD

**Issue by AtkociunaiteGreta** [mokymai/taisymai-2024#43]
### Nuoroda

https://mokymai.github.io/biostatistika/tyrimu-planavimas.html

### Ekrano nuotrauka su pažymėtais netikslumais

![Ekrano kopija (42)](https://github.com/user-attachments/assets/705bf1fb-fe0f-4a48-8d81-c0137045cc94)

### Netikslumo tipas

skyryba

### Netikslumo tekstas su keliais žodžiais aplinkui

Apie įvairius su statistika susijusius tyrimo planavimo

### Netikslumo tekstas

su statistika susijusius

### Siūlomas taisymo tekstas

,su statistika susijusius,

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Neprivaloma skyryba
