### ISSUE TITLE
[teorija]: visgi → visgi, (skyryba)

### ISSUE THREAD

**Issue by AtkociunaiteGreta** [mokymai/taisymai-2024#44]
### Nuoroda

https://mokymai.github.io/biostatistika/tyrimu-planavimas.html

### Ekrano nuotrauka su pažymėtais netikslumais

![Ekrano kopija (43)](https://github.com/user-attachments/assets/2724c4ae-e860-4bd4-86ca-1b6f8fd23ca2)

### Netikslumo tipas

skyryba

### Netikslumo tekstas su keliais žodžiais aplinkui

Visgi svarbu žinoti, kad kai kurie

### Netikslumo tekstas

Visgi svarbu žinoti

### Siūlomas taisymo tekstas

Visgi, svarbu žinoti, kad kai kurie eigos etapai gali persidengti.

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Neprivaloma skyryba:

https://www.vlkk.lt/konsultacijos/9697-modaliniai-zodziai

**Comment by GegznaV** [comment]
Neprivaloma skyryba
