### ISSUE TITLE
[BS-teorija]: paleista → paleistas ir artą → kartą (rašyba) [2.5 poskyris]

### ISSUE THREAD

**Issue by MartynasRi** [mokymai/taisymai-2024#5]
1. **Dalykas:** BS-2024 
2. **Netikslumo vieta:** Teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** https://mokymai.github.io/programa-r/paskyros.html
4. **Glaustai aprašykite netikslumą:** rašybos klaida ir nesuderinti linksniai
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** 
1- Gali būti, kad prisijungusiems pirmą kartą rodomas šiek tiek kitoks vaizdas nei įprastai: gali būti paleista susipažinimo su platforma gidas.
2- Kiekvieną artą prieš darydami užduotis įsitikinkite, kad esate prisijungę
6. **Netikslumo tekstas:** paleista | artą
7. **Siūlomas taisymo tekstas:** paleistas | kartą
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
1 - ![302234566-1b5995ee-929b-4f6b-b7dc-7b133be3bb83 (1)](https://github.com/mokymai/taisymai-2024/assets/158864974/b42ab058-d3a2-4490-b8da-30e3b7c1d611)
2 - ![302234287-efda5c4f-0a7a-44a8-a1ac-aaccf237303e](https://github.com/mokymai/taisymai-2024/assets/158864974/9e911ccc-6ce7-430d-bb17-4805303827e0)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Pateikdami klaidos pranešimą visada įdėkite kopijuojamą tekstą, nes reikia atlikti paiešką visoje sistemoje.

**Comment by GegznaV** [comment]
Taip pat pranešimo pavadinime privalo matytis, kokios tai klaidos.

**Comment by MartynasRi** [comment]
> Taip pat pranešimo pavadinime privalo matytis, kokios tai klaidos.

Papildyta.
