### ISSUE TITLE
[teorija]: nerodomos sukauptųjų dažnių formulės tekste

### ISSUE THREAD

**Issue by augustestankeviciute** [mokymai/taisymai-2024#58]
### Nuoroda

https://mokymai.github.io/konspektas/aprasomoji-1.html#sec-daznis

### Ekrano nuotrauka su pažymėtais netikslumais

![sukauptieji dazniai](https://github.com/user-attachments/assets/302c2a25-a37c-471b-8a6a-df80dfbd222a)

### Netikslumo tipas

kita

### Netikslumo tekstas su keliais žodžiais aplinkui

f_i^{\rm{ Sukauptieji gali būti tiek absoliutieji,

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [ ] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Kai nerodo formulių, reikia arba perkrauti svetainę (nes ne iki galo užsikrovė) arba yra dingęs internetas ir svetainę rodo iš laikinosios kompiuterio atminties. Jei nepadeda perkrovimas/interneto pajungimas, tada gali būti problemų su antivirusų arba ugniasiene.
