### ISSUE TITLE
[teorija]: Stjudento → Studento (rašyba)

### ISSUE THREAD

**Issue by ignedruskinyte** [mokymai/taisymai-2024#61]
### Nuoroda

https://mokymai.github.io/konspektas/aprasomoji-ivadas.html

### Ekrano nuotrauka su pažymėtais netikslumais

![Ekrano kopija 2024-09-17 092131](https://github.com/user-attachments/assets/a83203a6-17f0-4090-8fcb-a720dc3cacd0)

### Netikslumo tipas

rašyba (praleista raidė ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

 (pvz., Stjudento3 kriterijaus t statistika).

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by AugMark** [comment]
![image](https://github.com/user-attachments/assets/93bc573f-6fac-4e75-a393-3ddb2d1f7d69)

**Comment by GegznaV** [comment]
@AugMark, ar galėtumėte pasidalinti šaltinio nuoroda, jei jis internete?

**Comment by AugMark** [comment]
> @AugMark, ar galėtumėte pasidalinti šaltinio nuoroda, jei jis internete?

Šaltinis yra Lietuvos Respublikos terminų bankas: https://terminai.vlkk.lt/paieska?search=Stjudento
