### ISSUE TITLE
[pratybos]: skliaustų → kabučių (loginė klaida)

### ISSUE THREAD

**Issue by LauraMilak** [mokymai/taisymai-2024#63]
### Nuoroda

https://mokymai.github.io/biochemikams/s02.html

### Ekrano nuotrauka su pažymėtais netikslumais

<img width="425" alt="Screenshot 2024-09-17 at 11 29 33" src="https://github.com/user-attachments/assets/16c97ca1-a69e-4432-82e7-46447ac74c0c">

### Netikslumo tipas

fakto klaida

### Netikslumo tekstas su keliais žodžiais aplinkui

Paketo pavadinimą galima rašyti ir su, ir be skliaustų:

### Netikslumo tekstas

skliaustų

### Siūlomas taisymo tekstas

kabučių

### Dalykas

BS-2024

### Dėstytojas, kuris rengė medžiagą

Vilmantas

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Gera pastaba. Ačiū.
