### ISSUE TITLE
[BS-teorija]: vìsos → visos (rašybos klaida)

### ISSUE THREAD

**Issue by SaulePakne** [mokymai/taisymai-2024#7]
1. **Dalykas:** BS-2024
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/konspektas/01--01--pradines-savokos.html#sec-statistikos-sakos
4. **Glaustai aprašykite netikslumą:** Rašybos klaida  

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Reprezentatyvi imtis yra tokia, kurioje pakankamai tiksliai atsispindi vìsos GA savybės, svarbios tyrimui. 
6. **Netikslumo tekstas:** vìsos 
7. **Siūlomas taisymo tekstas:** visos
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...

<img width="492" alt="Fiksavimas" src="https://github.com/user-attachments/assets/b4746fc7-d69a-4cac-a60d-a9455c79b682">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Gal žinote geresnį variantą, kaip uždėti kairinį kirčio ženklą ant  „i“?
