### ISSUE TITLE
[teorija]: lygių dalių → lygias dalis (gramatika, nesuderinti linksniai)

### ISSUE THREAD

**Issue by AugustinusSkCh** [mokymai/taisymai-2024#76]
### Nuoroda

https://mokymai.github.io/konspektas/aprasomoji-1.html#sec-kvantiliai

### Ekrano nuotrauka su pažymėtais netikslumais

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/cf47e637-0b5c-4232-adec-0a9846ba997b">

### Netikslumo tipas

gramatika (nesuderinti linksniai ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

Procentiliai – reikšmės, variacinę seką dalijančios į 100 pagal elementų skaičių lygių dalių.

### Netikslumo tekstas

lygių dalių

### Siūlomas taisymo tekstas

lygias dalis

### Komentaras

Tekste nesuderinti linksniai, procentilių sąvoka skamba labai nelogiškai. Kvartilių sąvoka parašyta labai panašiai, bet ten linksniai yra suderinti.

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Ar turite omenyje: "į 100 (šimtą) lygias dalis"?

**Comment by AugustinusSkCh** [comment]
Rodos, kad taip.

**Comment by AugustinusSkCh** [comment]
> Ar turite omenyje: "į 100 (šimtą) lygias dalis"?

Rodos, kad taip.
