### ISSUE TITLE
[teorija]: teorinei → teoriniai (gramatika)

### ISSUE THREAD

**Issue by GerdaRum** [mokymai/taisymai-2024#78]
### Ekrano nuotrauka su pažymėtais netikslumais

<img width="1680" alt="Screenshot 2024-09-22 at 13 57 39" src="https://github.com/user-attachments/assets/78caa8e4-1f95-47ee-a124-175f241b5f16">

### Netikslumo tipas

gramatika (nesuderinti linksniai ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

Ši knyga-konspektas skirta teorinei daliai, kompiuterinių skaičiavimų dalis neįtraukta.

### Netikslumo tekstas

teorinei

### Siūlomas taisymo tekstas

teoriniai

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Nesuprantu, kur netikslumas. Juk "teorin**ė** dalis" → "teorin**ei** daliai". Bet būtų "teorin**iai**" skaičiavimai (nes "teorin**is**" skaičiavimas)
