### ISSUE TITLE
[teorija]: didum → didumą (rašybos klaida)

### ISSUE THREAD

**Issue by VaivaGMC** [mokymai/taisymai-2024#79]
### Nuoroda

https://mokymai.github.io/konspektas/aprasomoji-1.html#sec-reiksmiu-centras

### Ekrano nuotrauka su pažymėtais netikslumais

![image](https://github.com/user-attachments/assets/7507585e-fd80-42e0-b1ad-2132b132a210)

### Netikslumo tipas

rašyba (praleista raidė ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

Skrituliukai reprezentuoja pagal reikšmių didum išrikiuotus variacinės sekos narius. 

### Netikslumo tekstas

didum

### Siūlomas taisymo tekstas

didumą

### Dalykas

BS-2024

### Patvirtinimas

- [x] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [ ] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Pasikartojantis 
- #73
