### ISSUE TITLE
[BS-pratybos]: svariausia → svarbiausia (rašyba) [S01]

### ISSUE THREAD

**Issue by MartynasRi** [mokymai/taisymai-2024#80]
1. **Dalykas:** BS-2024
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/pratybos/s01.html#exr:01-calc-1
4. **Glaustai aprašykite netikslumą:** rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Šio kurso metu svariausia mokėti susikurti šių tipų dokumentus 
6. **Netikslumo tekstas:** svariausia
7. **Siūlomas taisymo tekstas:** svarbiausia
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![3](https://github.com/mokymai/taisymai-2024/assets/158864974/742436ef-6094-4be2-a2c8-107d5ebe3deb)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Ši klaida buvo neištaisyta nuo 2020!
