### ISSUE TITLE
[teorija]: grafikai → grafiniai (netinkamas terminas)

### ISSUE THREAD

**Issue by LauraKochanauskaite** [mokymai/taisymai-2024#80]
### Nuoroda

https://mokymai.github.io/konspektas/aprasomoji-ivadas#sec-skaitiniai-vs-grafiniai

### Ekrano nuotrauka su pažymėtais netikslumais

<img width="327" alt="image" src="https://github.com/user-attachments/assets/0d7842d3-6a99-475e-9f88-3245b1a1f9cd">

### Netikslumo tipas

netinkamas terminas

### Netikslumo tekstas su keliais žodžiais aplinkui

Grafikai - juose greičiau pastebime tendencijas bei anomalijas

### Netikslumo tekstas

Grafikai

### Siūlomas taisymo tekstas

Grafiniai

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
"Grafikai" arba "diagramos".
