### ISSUE TITLE
[teorija]: Grafikai → Grafiniai (netinkamas terminas)

### ISSUE THREAD

**Issue by LauraKochanauskaite** [mokymai/taisymai-2024#81]
### Nuoroda

https://mokymai.github.io/konspektas/aprasomoji-ivadas#sec-skaitiniai-vs-grafiniai

### Ekrano nuotrauka su pažymėtais netikslumais

<img width="332" alt="image" src="https://github.com/user-attachments/assets/dbe3767f-dad0-459c-909a-8c211500c767">

### Netikslumo tipas

netinkamas terminas

### Netikslumo tekstas su keliais žodžiais aplinkui

Grafikai ir skaitiniai metodai vieni kitus papildo.

### Netikslumo tekstas

Grafikai

### Siūlomas taisymo tekstas

Grafiniai

### Dalykas

BS-2024

### Patvirtinimas

- [X] Temos pavadinimą pakeičiau ir jame nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
"Grafikai" arba "diagramos" yra grafinių metodų rezultatai.
