### ISSUE TITLE
P04-1 (v1.0) sk._: atstumų→ atstumu (rašyba)

### ISSUE THREAD

**Issue by LauraKochanauskaite** [mokymai/taisymai-2024#92]
### Ekrano nuotrauka su pažymėtais netikslumais

<img width="440" alt="image" src="https://github.com/user-attachments/assets/1183ad42-b986-4937-870d-16a75942f9a5">

### Netikslumo tipas

rašyba (praleista raidė ar kt.)

### Netikslumo tekstas su keliais žodžiais aplinkui

centriniu momentu vadiname atstumų tarp kiekvienos imties....

### Netikslumo tekstas

atstumų

### Siūlomas taisymo tekstas

atstumu

### Dalykas

BS-2024

### Netikslumo vieta

skaidrės

### Patvirtinimas

- [X] Temos pavadinime nurodžiau skaidrių bloko kodą, versiją ir skaidrės numerį.
- [X] Temos pavadinime nurodžiau konkrečios problemos esmę.
- [X] Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji.

**Comment by GegznaV** [comment]
Pavadinime užpildykite šitą dalį, kad man ir kitiems studentams būtų galima identifikuoti, kur tiksliai yra klaida:

```
P__-_ (v1.0) sk._:
```

**Comment by GegznaV** [comment]
"Centriniu momentu vadiname atstumų sumą". Klaidos nematau, linksniai suderinti.
